# nginx/nginx.conf

# Configuration globale
events {
    worker_connections 1024;
}

http {
    # On inclut les types MIME pour que le CSS/JS soit bien reconnu
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            # On retire le =404 à la fin pour que React Router gère les routes
            try_files $uri $uri/ /index.html;
        }

    }
}